manager/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from manager.views import ManagerViewSet, ManagerProfile, IsValidManager, IsValidManagerPinCode

router = routers.DefaultRouter()
router.register(r'manager', ManagerViewSet)

urlpatterns = [
    url(r'^api/is_valid_manager/$', IsValidManager.as_view(), name='is_valid_manager'),
    url(r'^api/is_valid_manager_pin_code/$', IsValidManagerPinCode.as_view(), name='is_valid_manager_pin_code'),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<pk>\d+)/$', ManagerProfile.as_view(), name='manager_profile'),
]

msanitation/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from msanitation import settings

import administration.urls
import manager.urls
import provider.urls
import reporting.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from msanitation.views import Login, DashBoard, Profile, LogOut


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', LogOut.as_view(), name='logout'),
    url(r'^dashboard/$', DashBoard.as_view(), name='dashboard'),
    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^administration/', include(administration.urls)),
    url(r'^manager/', include(manager.urls)),
    url(r'^provider/', include(provider.urls)),
    url(r'^reporting/', include(reporting.urls)),
    url(r'^$', Login.as_view(), name='login_'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver


class UserProfile(models.Model):
    TYPE_CHOICES = (
        ('A', 'ADMINISTRATOR'),
        ('M', 'MANAGER'),
        ('P', 'PROVIDER')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    phone_number = models.CharField(max_length=20, null=True)
    address = models.TextField(null=True)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='P')

    def delete(self, *args, **kwargs):
        self.user.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __unicode__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, **kwargs):
    instance = kwargs['instance']
    if kwargs['created']:  # create
        UserProfile.objects.get_or_create(user=instance)


class Admin(models.Model):
    user_profile = models.OneToOneField(UserProfile, default=None, null=True)

    def delete(self, *args, **kwargs):
        self.user_profile.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __unicode__(self):
        return self.user_profile.user.username


class ProblemCategory(models.Model):
    index = models.IntegerField(unique=True, db_index=True)
    description = models.CharField(max_length=255)
    is_audio_recording = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.index) + ': ' + self.description

    class Meta:
        ordering = ('index',)


@receiver(post_save, sender=ProblemCategory)
def create_dummy_problem_for_audio_recording_category(sender, **kwargs):
    instance = kwargs['instance']
    if kwargs['created']:  # create
        if instance.is_audio_recording:
            Problem(index=1, description='Voice Recording', category=instance).save()


class Problem(models.Model):
    index = models.IntegerField(db_index=True)
    description = models.CharField(max_length=255)
    category = models.ForeignKey(ProblemCategory, related_name='problems')

    def __unicode__(self):
        return str(self.index) + ': ' + self.description + ' (Type ' + str(self.category.index) + ')'

    class Meta:
        unique_together = ("index", "category")
        index_together = ["index", "category"]
        ordering = ('index',)


class Toilet(models.Model):
    SEX_CHOICES = (
        ('B', 'Both'),
        ('M', 'Male'),
        ('F', 'Female')
    )
    AREA_CHOICES = (
        ('R', 'Rural'),
        ('U', 'Urban'),
        ('PU', 'Peri Urban')
    )
    PAY_CHOICES = (
        ('P', 'Paid'),
        ('F', 'Free'),
        ('B', 'Both (Pay + No Pay)'),
        ('H', 'Household Contribution')
    )
    TYPE_CHOICES = (
        ('C', 'Community'),
        ('P', 'Public'),
        ('S', 'School'),
        ('W', 'Women Sanitation Complex')
    )

    toilet_id = models.CharField(max_length=100, unique=True, db_index=True)
    address = models.TextField()

    sex = models.CharField(max_length=1, choices=SEX_CHOICES, default='B')
    payment = models.CharField(max_length=1, choices=PAY_CHOICES, default='F')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='P')
    area = models.CharField(max_length=2, choices=AREA_CHOICES, default='R')
    location_code = models.CharField(max_length=10, default='')

    def __unicode__(self):
        return str(self.toilet_id) + ': ' + self.address

manager/models.py
from django.db import models
from administration.models import UserProfile


class Manager(models.Model):
    MANAGER_CODE_CHOICES = (
        ('MC', 'MC: Municipal Commissioner'),
        ('MHO', 'MHO: Municipal Health Officer'),
        ('MSI', 'MSI: Municipal Sanitary Inspecter'),
        ('SS', 'SS: Sanitary Supervisor'),
        ('DRDA', 'DRDA: District Rural Development Agent'),
        ('BDO', 'BDO: Block District Officer'),
        ('TSC', 'TSC: Total Sanitation Coordinator (Block)'),
        ('SHM', 'SHM: School Head Master/Mistress')
    )

    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

    manager_id = models.CharField(max_length=100, unique=True, db_index=True)
    pin_code = models.CharField(max_length=10)
    description = models.TextField(blank=True, default='')
    manager_code = models.CharField(max_length=5, choices=MANAGER_CODE_CHOICES, default='MC')

    def delete(self, *args, **kwargs):
        self.user_profile.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __unicode__(self):
        return str(self.user_profile.user.first_name) + ' (' + self.user_profile.phone_number + ')'

    class Meta:
        index_together = ["manager_id", "pin_code"]
        ordering = ["user_profile__user__first_name"]

reporting/models.py
import uuid
from django.db import models

from administration.models import Problem, Toilet
from provider.models import Provider


class Ticket(models.Model):
    UNRESOLVED = 0
    FIXED = 1
    WONT_FIX = 2
    ESCALATED1 = 3
    ESCALATED2 = 4

    STATUS_CHOICES = (
        (0, 'Unresolved'),
        (1, 'Resolved'),
        (2, 'Cannot fix'),
        (3, 'Escalated'),
    )

    ticket_id = models.CharField(max_length=40, unique=True, db_index=True, default=uuid.uuid4)
    phone_number = models.CharField(max_length=15)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    toilet = models.ForeignKey(Toilet, related_name='tickets')
    problem = models.ForeignKey(Problem, related_name='tickets')
    provider = models.ForeignKey(Provider, related_name='tickets', null=True, blank=True, on_delete=models.SET_NULL)
    status = models.IntegerField(default=UNRESOLVED)
    is_audio_present = models.BooleanField(default=False)
    is_provider_audio_present = models.BooleanField(default=False)
    provider_remarks = models.TextField(blank=True, default='')
    user_remarks = models.TextField(blank=True, default='')
    manager_remarks = models.TextField(blank=True, default='')
    complaints = models.IntegerField(default=1)
    additional_complaints_info = models.CharField(max_length=65000)
    

    def __unicode__(self):
        return str(self.id)

    class Meta:
        ordering = ['-timestamp']

manager/forms.py
from django.forms import ModelForm
from .models import Manager


class ManagerForm(ModelForm):
    class Meta:
        model = Manager
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ManagerForm, self).__init__(*args, **kwargs)
        self.fields['manager_code'].widget.attrs.update({
            'class': 'form-control',
            'required': 'required'
        })

manager/views.py
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView
from django.views.generic import View
from django.shortcuts import render

from manager.models import Manager
from manager.serializers import ManagerSerializer


class ManagerViewSet(viewsets.ModelViewSet):
    queryset = Manager.objects.all()
    serializer_class = ManagerSerializer


class ManagerProfile(View):
    def get(self, request, pk):
        manager = Manager.objects.get(pk=pk)
        return render(request, 'administration/profile.html', {'user': manager})


class IsValidManager(APIView):
    def post(self, request):
        manager_id = request.data.get('manager_id', None)
        if not manager_id:
            return Response({'success': False, 'error': "Invalid POST data"})
        try:
            Manager.objects.get(manager_id=manager_id)
        except (Manager.DoesNotExist, Manager.MultipleObjectsReturned):
            return Response({'success': False, 'error': "Invalid Manager ID"})
        return Response({'success': True})


class IsValidManagerPinCode(APIView):
    def post(self, request):
        manager_id = request.data.get('manager_id', None)
        pin_code = request.data.get('pin_code', None)
        if not manager_id or not pin_code:
            return Response({'success': False, 'error': "Invalid POST data"})
        try:
            Manager.objects.get(manager_id=manager_id, pin_code=pin_code)
        except (Manager.DoesNotExist, Manager.MultipleObjectsReturned):
            return Response({'success': False, 'error': "Invalid Manager ID/PIN Code"})
        return Response({'success': True})

manager/templates/manager/profile.html
{% extends 'sidebar.html' %}

{% load staticfiles %}

{% block pageContent %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="page-title">
            <div class="title_left">
                <h3>Edit Profile</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <br/>
                        <form method="POST" data-parsley-validate class="form-horizontal form-label-left" novalidate
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Error -->
                            {% if error %}
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <label class="text-danger">{{ error }}</label>
                                    </div>
                                </div>
                            {% endif %}
                            <!-- /Error -->
                            <!-- First Name -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_first_name">First Name
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="id_first_name" name="first_name" required="required"
                                           class="form-control col-md-7 col-xs-12" value="{{ user.user.first_name }}">
                                </div>
                            </div>
                            <!-- /First Name -->
                            <!-- Last Name -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_last_name">Last Name
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="id_last_name" name="last_name" class="form-control
                                            col-md-7 col-xs-12" value="{{ user.user.last_name }}">
                                </div>
                            </div>
                            <!-- /Last Name -->
                            <!-- Username -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_username">Username
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" disabled="disabled" class="form-control col-md-7 col-xs-12" value="{{ user.user.username }}">
                                </div>
                            </div>
                            <!-- /Username -->
                            <!-- Password -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_password">Password
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" id="id_password" name="password"
                                           class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <!-- /Password -->
                            <!-- Manager ID -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_manager_id">Manager ID
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" disabled="disabled" class="form-control col-md-7 col-xs-12" value="{{ manager.manager_id }}">
                                </div>
                            </div>
                            <!-- /Manager ID -->
                            <!-- PIN -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_pin_code">PIN
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" id="id_pin_code" name="pin_code"
                                           class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <!-- /PIN -->
                            <!-- Email -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_email">Email</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="email" id="id_email" name="email"
                                           class="form-control col-md-7 col-xs-12" value="{{ user.user.email }}">
                                </div>
                            </div>
                            <!-- /Email -->
                            <!-- PhoneNumber -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="id_phone_number">Phone Number <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ user_profile_form.phone_number }}
                                </div>
                            </div>
                            <!-- /PhoneNumber -->
                            <!-- Address -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_address">Address
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ user_profile_form.address }}
                                </div>
                            </div>
                            <!-- /Address -->
                            <!-- Profile_Picture -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="id_picture">Profile Picture
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ user_profile_form.picture }}
                                </div>
                            </div>
                            <!-- /Profile_Picture -->
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <a href="{% url 'dashboard' %}" class="btn btn-primary">Cancel</a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock %}

{% block jsLinks %}
    <!-- validation -->
    <script src="{% static "vendors/parsleyjs/dist/parsley.min.js" %}"></script>
    <!-- /validation -->
{% endblock %}