manager/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from manager.views import ManagerViewSet, ManagerProfile, IsValidManager, IsValidManagerPinCode

router = routers.DefaultRouter()
router.register(r'manager', ManagerViewSet)

urlpatterns = [
    url(r'^api/is_valid_manager/$', IsValidManager.as_view(), name='is_valid_manager'),
    url(r'^api/is_valid_manager_pin_code/$', IsValidManagerPinCode.as_view(), name='is_valid_manager_pin_code'),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<pk>\d+)/$', ManagerProfile.as_view(), name='manager_profile'),
]

msanitation/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from msanitation import settings

import administration.urls
import manager.urls
import provider.urls
import reporting.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from msanitation.views import Login, DashBoard, Profile, LogOut


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', LogOut.as_view(), name='logout'),
    url(r'^dashboard/$', DashBoard.as_view(), name='dashboard'),
    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^administration/', include(administration.urls)),
    url(r'^manager/', include(manager.urls)),
    url(r'^provider/', include(provider.urls)),
    url(r'^reporting/', include(reporting.urls)),
    url(r'^$', Login.as_view(), name='login_'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reporting/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from reporting.views import TicketViewSet, IsValidToilet, IsValidProviderTicket, ReportProblem, ReportProblemAPI, \
    ReportFix, DownloadAudio, GetAudioURL, IsValidManagerTicket

router = routers.DefaultRouter()
router.register(r'ticket', TicketViewSet)

urlpatterns = [
    url(r'^api/is_valid_toilet/$', IsValidToilet.as_view(), name='is_valid_toilet'),
    url(r'^api/is_valid_provider_ticket/$', IsValidProviderTicket.as_view(), name='is_valid_provider_ticket'),
    url(r'^api/is_valid_manager_ticket/$', IsValidManagerTicket.as_view(), name='is_valid_manager_ticket'),
    url(r'^api/report_problem/$', ReportProblemAPI.as_view(), name='report_problem_api'),
    url(r'^api/report_fix/$', ReportFix.as_view(), name='report_fix'),
    url(r'^api/download_audio/$', DownloadAudio.as_view(), name='download_audio'),
    url(r'^api/get_audio_url/$', GetAudioURL.as_view(), name='get_audio_url'),

    url(r'^report_problem/$', ReportProblem.as_view(), name='report_problem'),
    url(r'^report_problem/(?P<ticket_id>\d+)/$', ReportProblem.as_view(), name='report_problem_ticket'),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

reporting/models.py
import uuid
from django.db import models

from administration.models import Problem, Toilet
from provider.models import Provider


class Ticket(models.Model):
    UNRESOLVED = 0
    FIXED = 1
    WONT_FIX = 2
    ESCALATED1 = 3
    ESCALATED2 = 4

    STATUS_CHOICES = (
        (0, 'Unresolved'),
        (1, 'Resolved'),
        (2, 'Cannot fix'),
        (3, 'Escalated'),
    )

    ticket_id = models.CharField(max_length=40, unique=True, db_index=True, default=uuid.uuid4)
    phone_number = models.CharField(max_length=15)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    toilet = models.ForeignKey(Toilet, related_name='tickets')
    problem = models.ForeignKey(Problem, related_name='tickets')
    provider = models.ForeignKey(Provider, related_name='tickets', null=True, blank=True, on_delete=models.SET_NULL)
    status = models.IntegerField(default=UNRESOLVED)
    is_audio_present = models.BooleanField(default=False)
    is_provider_audio_present = models.BooleanField(default=False)
    provider_remarks = models.TextField(blank=True, default='')
    user_remarks = models.TextField(blank=True, default='')
    manager_remarks = models.TextField(blank=True, default='')
    complaints = models.IntegerField(default=1)
    additional_complaints_info = models.CharField(max_length=65000)
    

    def __unicode__(self):
        return str(self.id)

    class Meta:
        ordering = ['-timestamp']

administration/forms.py
from django.forms import ModelForm, ChoiceField
from django import forms
from .models import Admin, Problem, ProblemCategory, Toilet, UserProfile
from reporting.models import Ticket
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class AdminForm(ModelForm):
    class Meta:
        model = Admin
        fields = '__all__'


class ProblemCategoryForm(ModelForm):
    class Meta:
        model = ProblemCategory
        fields = '__all__'


class ProblemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProblemForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('submit', 'Add Problem'))

    class Meta:
        model = Problem
        fields = '__all__'


class ToiletForm(ModelForm):
    class Meta:
        model = Toilet
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ToiletForm, self).__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
            'required': 'required'
        })
        self.fields['toilet_id'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['sex'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['payment'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['type'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['area'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['location_code'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })


class TicketForm(ModelForm):
    status = ChoiceField(choices=Ticket.STATUS_CHOICES, required=True)
    problem_category = forms.ModelChoiceField(queryset=ProblemCategory.objects.all())

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.fields['ticket_id'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
        })
        self.fields['toilet'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['problem'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['provider'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
        })
        self.fields['status'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['provider_remarks'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
        })
        self.fields['user_remarks'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
        })
        self.fields['manager_remarks'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
        })
        self.fields['problem_category'].widget.attrs.update({
            'class': 'form-control',
            'required': 'required'
        })


    class Meta:
        model = Ticket
        exclude = []


class UserForm(ModelForm):
    class Meta:
        model = Toilet
        fields = '__all__'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['address'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
            'required': 'required'
        })
        self.fields['picture'].widget.attrs.update({
            'class': 'form-control',
            'style': 'border: 0px',
            'accept': 'image'
        })

reporting/templates/reporting/report_problem.html
{% extends 'sidebar.html' %}

{% load staticfiles %}

{% block pageContent %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="page-title">
            <div class="title_left">
                <h3>Add/Edit Ticket</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <br/>
                        <form method="POST" data-parsley-validate class="form-horizontal form-label-left" novalidate
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Error -->
                            {% if error %}
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <label class="text-danger">{{ error }}</label>
                                    </div>
                                </div>
                            {% endif %}
                            <!-- /Error -->
                            <!-- Message -->
                            {% if message %}
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <label class="text-success">{{ message }}</label>
                                    </div>
                                </div>
                            {% endif %}
                            <!-- /Message -->
                            {% if ticket_form %}
                                {% if ticket_form.instance.id %}
                                    <!-- Ticket ID -->
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Ticket ID</label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <label class="form-control col-md-7 col-xs-12">
                                                {{ ticket_form.instance.id }}
                                            </label>
                                        </div>
                                    </div>
                                    <!-- /Ticket ID -->
                                {% endif %}
                                <!-- PhoneNumber -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_phone_number">
                                        Phone Number
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.phone_number }}
                                    </div>
                                </div>
                                <!-- /PhoneNumber -->
                                <!-- Toilet -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_toilet">Toilet
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.toilet }}
                                    </div>
                                </div>
                                <!-- /Toilet -->
                                <!-- ProblemType -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_problem_category">Problem Type
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.problem_category }}
                                    </div>
                                </div>
                                <!-- /ProblemType -->
                                <!-- Problem -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_problem">Problem
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.problem }}
                                    </div>
                                </div>
                                <!-- /Problem -->
                                <!-- Provider -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_provider">Provider
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.provider }}
                                    </div>
                                </div>
                                <!-- /Provider -->
                                <!-- Provider Remarks -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_provider_remarks">Provider Remarks
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.provider_remarks }}
                                    </div>
                                </div>
                                <!-- /Provider Remarks -->
                                <!-- User Remarks -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_user_remarks">User Remarks
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.user_remarks }}
                                    </div>
                                </div>
                                <!-- /User Remarks -->
                                <!-- Manager Remarks -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_manager_remarks">Manager Remarks
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.manager_remarks }}
                                    </div>
                                </div>
                                <!-- /Manager Remarks -->
                                <!-- Status -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_toilet">Status
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ ticket_form.status }}
                                    </div>
                                </div>
                                <!-- /Status -->
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        <a href="{% url 'dashboard' %}" class="btn btn-primary">Cancel</a>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock %}

{% block jsLinks %}
    <!-- validation -->
    <script src="{% static "vendors/parsleyjs/dist/parsley.min.js" %}"></script>
    <!-- /validation -->
    <script type="text/javascript">
    $(document).ready(function() {
        $('#id_problem_category').change(function() {
            var selected_category = $(this).prop('value');
            var selected = false;
            var check_string = 'Type ' + selected_category;
            if(selected_category == '')
                check_string = 'Type X';
            $('#id_problem option').each(function() {
                $(this)[0].selected = false;
                if($(this).text().indexOf(check_string) != -1) {
                    $(this).show();
                    if(!selected) {
                        $(this)[0].selected = true;
                        selected = true;
                    }
                } else {
                    $(this).hide();
                }
            });
        });
    });
    </script>
{% endblock %}