administration/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from administration.views import AdminViewSet, ProblemCategoryViewSet, ProblemViewSet, ToiletViewSet,\
    ViewManagers, AddManager, ViewManager, DeleteManager, EditManager,\
    ViewProviders, AddProvider, ViewProvider, DeleteProvider, EditProvider,\
    ViewToilets, AddToilet, EditToilet, DeleteToilet , ShowComplaints, DisplayStats

router = routers.DefaultRouter()
router.register(r'admin', AdminViewSet)
router.register(r'problem-category', ProblemCategoryViewSet)
router.register(r'problem', ProblemViewSet)
router.register(r'toilet', ToiletViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^view_managers/$', ViewManagers.as_view(), name='view_managers'),
    url(r'^view_manager/(?P<manager_id>\d+)/$', ViewManager.as_view(), name='view_manager'),
    url(r'^add_manager/$', AddManager.as_view(), name='add_manager'),
    url(r'^edit_manager/(?P<manager_id>\d+)/$', EditManager.as_view(), name='edit_manager'),
    url(r'^delete_manager/(?P<manager_id>\d+)/$', DeleteManager.as_view(), name='delete_manager'),

    url(r'^view_providers/$', ViewProviders.as_view(), name='view_providers'),
    url(r'^view_provider/(?P<provider_id>\d+)/$', ViewProvider.as_view(), name='view_provider'),
    url(r'^add_provider/$', AddProvider.as_view(), name='add_provider'),
    url(r'^edit_provider/(?P<provider_id>\d+)/$', EditProvider.as_view(), name='edit_provider'),
    url(r'^delete_provider/(?P<provider_id>\d+)/$', DeleteProvider.as_view(), name='delete_provider'),

    url(r'^view_toilets/$', ViewToilets.as_view(), name='view_toilets'),
    url(r'^add_toilet/$', AddToilet.as_view(), name='add_toilet'),
    url(r'^edit_toilet/(?P<toilet_id>\d+)/$', EditToilet.as_view(), name='edit_toilet'),
    url(r'^delete_toilet/(?P<toilet_id>\d+)/$', DeleteToilet.as_view(), name='delete_toilet'),

    url(r'^complaints/(?P<ticket_id>\d+)/$', ShowComplaints.as_view(), name='complaints'),

    url(r'^stats/$', DisplayStats.as_view(), name='stats'),

]

manager/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from manager.views import ManagerViewSet, ManagerProfile, IsValidManager, IsValidManagerPinCode

router = routers.DefaultRouter()
router.register(r'manager', ManagerViewSet)

urlpatterns = [
    url(r'^api/is_valid_manager/$', IsValidManager.as_view(), name='is_valid_manager'),
    url(r'^api/is_valid_manager_pin_code/$', IsValidManagerPinCode.as_view(), name='is_valid_manager_pin_code'),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<pk>\d+)/$', ManagerProfile.as_view(), name='manager_profile'),
]

msanitation/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from msanitation import settings

import administration.urls
import manager.urls
import provider.urls
import reporting.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from msanitation.views import Login, DashBoard, Profile, LogOut


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', LogOut.as_view(), name='logout'),
    url(r'^dashboard/$', DashBoard.as_view(), name='dashboard'),
    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^administration/', include(administration.urls)),
    url(r'^manager/', include(manager.urls)),
    url(r'^provider/', include(provider.urls)),
    url(r'^reporting/', include(reporting.urls)),
    url(r'^$', Login.as_view(), name='login_'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver


class UserProfile(models.Model):
    TYPE_CHOICES = (
        ('A', 'ADMINISTRATOR'),
        ('M', 'MANAGER'),
        ('P', 'PROVIDER')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    phone_number = models.CharField(max_length=20, null=True)
    address = models.TextField(null=True)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='P')

    def delete(self, *args, **kwargs):
        self.user.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __unicode__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, **kwargs):
    instance = kwargs['instance']
    if kwargs['created']:  # create
        UserProfile.objects.get_or_create(user=instance)


class Admin(models.Model):
    user_profile = models.OneToOneField(UserProfile, default=None, null=True)

    def delete(self, *args, **kwargs):
        self.user_profile.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __unicode__(self):
        return self.user_profile.user.username


class ProblemCategory(models.Model):
    index = models.IntegerField(unique=True, db_index=True)
    description = models.CharField(max_length=255)
    is_audio_recording = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.index) + ': ' + self.description

    class Meta:
        ordering = ('index',)


@receiver(post_save, sender=ProblemCategory)
def create_dummy_problem_for_audio_recording_category(sender, **kwargs):
    instance = kwargs['instance']
    if kwargs['created']:  # create
        if instance.is_audio_recording:
            Problem(index=1, description='Voice Recording', category=instance).save()


class Problem(models.Model):
    index = models.IntegerField(db_index=True)
    description = models.CharField(max_length=255)
    category = models.ForeignKey(ProblemCategory, related_name='problems')

    def __unicode__(self):
        return str(self.index) + ': ' + self.description + ' (Type ' + str(self.category.index) + ')'

    class Meta:
        unique_together = ("index", "category")
        index_together = ["index", "category"]
        ordering = ('index',)


class Toilet(models.Model):
    SEX_CHOICES = (
        ('B', 'Both'),
        ('M', 'Male'),
        ('F', 'Female')
    )
    AREA_CHOICES = (
        ('R', 'Rural'),
        ('U', 'Urban'),
        ('PU', 'Peri Urban')
    )
    PAY_CHOICES = (
        ('P', 'Paid'),
        ('F', 'Free'),
        ('B', 'Both (Pay + No Pay)'),
        ('H', 'Household Contribution')
    )
    TYPE_CHOICES = (
        ('C', 'Community'),
        ('P', 'Public'),
        ('S', 'School'),
        ('W', 'Women Sanitation Complex')
    )

    toilet_id = models.CharField(max_length=100, unique=True, db_index=True)
    address = models.TextField()

    sex = models.CharField(max_length=1, choices=SEX_CHOICES, default='B')
    payment = models.CharField(max_length=1, choices=PAY_CHOICES, default='F')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='P')
    area = models.CharField(max_length=2, choices=AREA_CHOICES, default='R')
    location_code = models.CharField(max_length=10, default='')

    def __unicode__(self):
        return str(self.toilet_id) + ': ' + self.address

manager/models.py
from django.db import models
from administration.models import UserProfile


class Manager(models.Model):
    MANAGER_CODE_CHOICES = (
        ('MC', 'MC: Municipal Commissioner'),
        ('MHO', 'MHO: Municipal Health Officer'),
        ('MSI', 'MSI: Municipal Sanitary Inspecter'),
        ('SS', 'SS: Sanitary Supervisor'),
        ('DRDA', 'DRDA: District Rural Development Agent'),
        ('BDO', 'BDO: Block District Officer'),
        ('TSC', 'TSC: Total Sanitation Coordinator (Block)'),
        ('SHM', 'SHM: School Head Master/Mistress')
    )

    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

    manager_id = models.CharField(max_length=100, unique=True, db_index=True)
    pin_code = models.CharField(max_length=10)
    description = models.TextField(blank=True, default='')
    manager_code = models.CharField(max_length=5, choices=MANAGER_CODE_CHOICES, default='MC')

    def delete(self, *args, **kwargs):
        self.user_profile.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __unicode__(self):
        return str(self.user_profile.user.first_name) + ' (' + self.user_profile.phone_number + ')'

    class Meta:
        index_together = ["manager_id", "pin_code"]
        ordering = ["user_profile__user__first_name"]

provider/models.py
from django.db import models

from administration.models import ProblemCategory, Toilet, UserProfile
from manager.models import Manager


class Provider(models.Model):
    PROVIDER_CODE_CHOICES = (
        ('CLR', 'CLR: Cleaner'),
        ('CTR', 'CTR: Caretaker'),
        ('PLB', 'PLB: Plumber'),
        ('SEW', 'SEW: Sewage Management'),
        ('MGR', 'MGR: Water Management'),
        ('VOL', 'VOL: Volunteer'),
        ('CON', 'CON: Contractor'),
        ('MWM', 'MWM: Municipal Ward Member'),
        ('NGO', 'NGO: Non-Govt. Organization')
    )

    user_profile = models.OneToOneField(UserProfile)

    provider_id = models.CharField(max_length=100, unique=True, db_index=True)
    pin_code = models.CharField(max_length=10)
    manager = models.ForeignKey(Manager, related_name='providers', on_delete=models.CASCADE)
    toilets = models.ManyToManyField(Toilet, related_name='providers')
    problems = models.ManyToManyField(ProblemCategory, related_name='providers')
    description = models.TextField(blank=True, default='')
    provider_code = models.CharField(max_length=5, choices=PROVIDER_CODE_CHOICES, default='CLR')

    def __unicode__(self):
        return "%s %s (%s)" % (
            self.user_profile.user.first_name, self.user_profile.user.last_name, self.user_profile.phone_number)

    def delete(self, *args, **kwargs):
        self.user_profile.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    class Meta:
        index_together = ["provider_id", "pin_code"]
        ordering = ['user_profile__user__first_name']

administration/forms.py
from django.forms import ModelForm, ChoiceField
from django import forms
from .models import Admin, Problem, ProblemCategory, Toilet, UserProfile
from reporting.models import Ticket
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class AdminForm(ModelForm):
    class Meta:
        model = Admin
        fields = '__all__'


class ProblemCategoryForm(ModelForm):
    class Meta:
        model = ProblemCategory
        fields = '__all__'


class ProblemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProblemForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('submit', 'Add Problem'))

    class Meta:
        model = Problem
        fields = '__all__'


class ToiletForm(ModelForm):
    class Meta:
        model = Toilet
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ToiletForm, self).__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
            'required': 'required'
        })
        self.fields['toilet_id'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['sex'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['payment'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['type'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['area'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['location_code'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })


class TicketForm(ModelForm):
    status = ChoiceField(choices=Ticket.STATUS_CHOICES, required=True)
    problem_category = forms.ModelChoiceField(queryset=ProblemCategory.objects.all())

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.fields['ticket_id'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
        })
        self.fields['toilet'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['problem'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['provider'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
        })
        self.fields['status'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['provider_remarks'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
        })
        self.fields['user_remarks'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
        })
        self.fields['manager_remarks'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
        })
        self.fields['problem_category'].widget.attrs.update({
            'class': 'form-control',
            'required': 'required'
        })


    class Meta:
        model = Ticket
        exclude = []


class UserForm(ModelForm):
    class Meta:
        model = Toilet
        fields = '__all__'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control col-md-7 col-xs-12',
            'required': 'required'
        })
        self.fields['address'].widget.attrs.update({
            'rows': 3,
            'class': 'form-control',
            'required': 'required'
        })
        self.fields['picture'].widget.attrs.update({
            'class': 'form-control',
            'style': 'border: 0px',
            'accept': 'image'
        })

administration/templates/administration/add_provider.html
{% extends 'sidebar.html' %}

{% load staticfiles %}

{% block pageContent %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="page-title">
            <div class="title_left">
                <h3>Add Provider</h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <br/>
                        <form method="POST" data-parsley-validate class="form-horizontal form-label-left" novalidate
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Error -->
                            {% if error %}
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <label class="text-danger">{{ error }}</label>
                                    </div>
                                </div>
                            {% endif %}
                            <!-- /Error -->
                            <!-- First Name -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_first_name">First Name
                                            <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="id_first_name" name="first_name" required="required"
                                           class="form-control col-md-7 col-xs-12"{% if first_name %} value="{{ first_name }}"{% endif %}>
                                </div>
                            </div>
                            <!-- /First Name -->
                            <!-- Last Name -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_last_name">Last Name
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="id_last_name" name="last_name" class="form-control
                                            col-md-7 col-xs-12"{% if last_name %} value="{{ last_name }}"{% endif %}>
                                </div>
                            </div>
                            <!-- /Last Name -->
                            <!-- Username -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_username">Username
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                {% if username %}
                                    <input type="text" disabled="disabled" class="form-control col-md-7 col-xs-12" value="{{ username }}">
                                    <input type="hidden" name="username" value="{{ username }}">
                                {% else %}
                                    <input type="text" id="id_username" name="username" required="required"
                                           class="form-control col-md-7 col-xs-12">
                                {% endif %}
                                </div>
                            </div>
                            <!-- /Username -->
                            <!-- Password -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_password">Password
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" id="id_password" name="password"
                                           class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <!-- /Password -->
                            <!-- Provider Code -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_provider_code">Provider Code
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ provider_form.provider_code }}
                                </div>
                            </div>
                            <!-- /Provider Code -->
                            <!-- ProviderID -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_provider_id">Provider ID
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                {% if provider_id %}
                                    <input type="text" disabled="disabled" class="form-control col-md-7 col-xs-12" value="{{ provider_id }}">
                                    <input type="hidden" name="provider_id" value="{{ provider_id }}">
                                {% else %}
                                    <input type="text" id="id_provider_id" name="provider_id" required="required"
                                           class="form-control col-md-7 col-xs-12">
                                {% endif %}
                                </div>
                            </div>
                            <!-- /ProviderID -->
                            <!-- PinCode -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_pin_code">PIN
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" id="id_pin_code" name="pin_code" required="required"
                                           class="form-control col-md-7 col-xs-12"{% if pin_code %} value="{{ pin_code }}"{% endif %}>
                                </div>
                            </div>
                            <!-- /PinCode -->
                            <!-- Description -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_description">Description
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ provider_form.description }}
                                </div>
                            </div>
                            <!-- /Description -->
                            <!-- Email -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_email">Email</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="email" id="id_email" name="email"
                                           class="form-control col-md-7 col-xs-12"{% if email %} value="{{ email }}"{% endif %}>
                                </div>
                            </div>
                            <!-- /Email -->
                            <!-- PhoneNumber -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="id_phone_number">Phone Number <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ user_profile_form.phone_number }}
                                </div>
                            </div>
                            <!-- /PhoneNumber -->
                            <!-- Manager -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="id_manager">Manager <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ provider_form.manager }}
                                </div>
                            </div>
                            <!-- /Manager -->
                            <!-- Toilets -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_toilets">Toilets
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ provider_form.toilets }}
                                </div>
                            </div>
                            <!-- /Toilets -->
                            <!-- Problems -->
                            <div class="form-group">
                                <div class="col-md-offset-3 col-sm-offset-3 col-md-6 col-sm-6 col-xs-12">
                                    <input type="checkbox" id="select_all_problems"/>
                                    <label for="select_all_problems"> Select/Unselect all problems</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_problems">Problems
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ provider_form.problems }}
                                </div>
                            </div>
                            <!-- /Problems -->
                            <!-- Address -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_address">Address
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ user_profile_form.address }}
                                </div>
                            </div>
                            <!-- /Address -->
                            <!-- Profile_Picture -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="id_picture">Profile Picture
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ user_profile_form.picture }}
                                </div>
                            </div>
                            <!-- /Profile_Picture -->
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <a href="{% url 'view_providers' %}" class="btn btn-primary">Cancel</a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock %}

{% block jsLinks %}
    <!-- validation -->
    <script src="{% static "vendors/parsleyjs/dist/parsley.min.js" %}"></script>
    <!-- /validation -->
    <script type="text/javascript">
        $(document).ready(function() {
            $('#select_all_problems').change(function() {
                if($(this).is(":checked")) {
                    $('#id_problems option').prop('selected', true);
                } else {
                    $('#id_problems option').prop('selected', false);
                }
            });
            $('#id_problems').change(function() {
                if($("#id_problems :not(:selected)").length == 0) {
                    $('#select_all_problems').prop('checked', true);
                } else {
                    $('#select_all_problems').prop('checked', false);
                }
            });
        });
    </script>
{% endblock %}